changed from ARGF.read to ARGF.readlines.  read only works in ruby 1.8.7, causes following exception in ruby 1.9.3.  tested readlines in both 1.8.7 and 1.9.3 and it works.
./ocunit2junit.rb:48:in `parse_input': undefined method `each' for #<String:0x007faf2c03bf78> (NoMethodError)
	from ./ocunit2junit.rb:42:in `initialize'
		from ./ocunit2junit.rb:160:in `new'
			from ./ocunit2junit.rb:160:in `<main>'